environment:
  matrix:
    - nodejs_version: 0.8
    - nodejs_version: 0.10

platform:
  - x86

install:
  - ps: Install-Product node $env:nodejs_version $env:Platform
  - node --version
  - npm --version
  - cmd: SET PATH=c:\python27;%PATH%
  - npm install
  - npm test